name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
    - name: Install libpcap-dev
      run: sudo apt-get install libpcap-dev
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get .
    - name: Run unit test
      run: go test ./... -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    - name: Run build
      run: go build -v .
  build-artifact-darwin:
    needs: test-build
    name: Build executable for ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: macos-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: ["386", amd64]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get .
    - name: Run go build
      run: go build -o .
      env:
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: "inkle-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.sha }}"
        path: ./inkle
      
