on: 
  release:
    types: [published]
name: release
jobs:
  push-docker:
    name: Build and push to docker registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: abrampers/inkle
        tag_with_ref: true
